const currentTypes = {
  GET_DATA:'CURRENT TYPES GET DATA',
  SELECT_OPTIONS:'CURRENT TYPES SELECT OPTIONS',
  RECEIVE_DATA_FROM_WS:'CURRENT TYPES RECEIVE DATA FROM WS',
  REFRESH_REDUCER:'CURRENT TYPES REFRESH REDUCER',
  CHANGE_LINE_CHART_DATA:'CURRENT TYPES CHANGE LINECHART DATA'
}
export default currentTypes