const dashboardTypes = {
  GET_DATA_VOLTAGE:'DASHBOARD TYPES GET DATA VOLTAGE',
  GET_DATA_CURRENT:'DASHBOARD TYPES GET DATA CURRENT',
  GET_DATA_POWER:'DASHBOARD TYPES GET DATA POWER',
  GET_DATA_ENERGY:'DASHBOARD TYPES GET DATA ENERGY',
  GET_DATA_GAUGE_CHART:'DASHBOARD TYPES GET DATA GAUGE CHART',
  CHANGE_GAUGE_DATA:'DASHBOARD TYPES CHANGE GAUGE DATA',
  CHANGE_LINE_CHART_DATA:'DASHBOARD TYPES CHANGE LINE CHART DATA',
  REFRESH_REDUCER:'DASHBOARD TYPES REFRESH REDUCER'
}
export default dashboardTypes