const energyTypes = {
  GET_DATA:'ENERGY TYPES GET DATA',
  SELECT_OPTIONS:'ENERGY TYPES SELECT OPTIONS',
  RECEIVE_DATA_FROM_WS:'ENERGY TYPES RECEIVE DATA FROM WS',
  REFRESH_REDUCER:'ENERGY TYPES REFRESH REDUCER',
  CHANGE_LINE_CHART_DATA:'ENERGY TYPES CHANGE LINECHART DATA'
}
export default energyTypes