const settingsTypes = {
  ONCHANGE_DATAITEM:'SETTINGS TYPES CHANGE SETTINGS',
  INITIALIZE_SETTINGS:'SETTINGS TYPES INITIALIZE SETTINGS',
  ONCLICK_EDIT:'SETTINGS TYPES ONCLICK EDIT',
  ON_DISCARD:'SETTINGS TYPES ON DISCARD',
  ON_SAVE:'SETTINGS ONSAVE DATAITEM'
}
export default settingsTypes