const settingsTypes = {
  ONCHANGE_DATAITEM:'SETTINGS TYPES CHANGE SETTINGS',
  INITIALIZE_SETTINGS:'SETTINGS TYPES INITIALIZE SETTINGS',
  INITIALIZE_NAVBAR:'SETTING TYPES INITIALIZE NAVBAR',
  CHANGE_GATEWAY:'SETTINGS TYPES CHANGE GATEWAY OPTIONS',

  ONCLICK_EDIT:'SETTINGS TYPES ONCLICK EDIT',
  ON_DISCARD:'SETTINGS TYPES ON DISCARD',
  ON_SAVE:'SETTINGS ONSAVE DATAITEM',

  ON_GATEWAY_EDIT:'SETTINGS TYPE ON GATEWAY EDIT',
  ON_GATEWAY_DISCARD:'SETTINGS TYPES ON GATEWAY DISCARD',
  ON_GATEWAY_SAVE:'SETTINGS TYPES ON GATEWAY SAVE',
  ON_CHANGE_GATEWAY_NAME:'SETTINGS TYPES ON CHANGE GATEWAY NAME'
}
export default settingsTypes