const voltageTypes = {
  GET_DATA:'VOLTAGE TYPES GET DATA',
  SELECT_OPTIONS:'VOLTAGE TYPES SELECT OPTIONS',
  RECEIVE_DATA_FROM_WS:'VOLTAGE TYPES RECEIVE DATA FROM WS',
  REFRESH_REDUCER:'VOLTAGE TYPES REFRESH REDUCER',
  CHANGE_LINE_CHART_DATA:'VOLTAGE_TYPES CHANGE LINECHART DATA'
}
export default voltageTypes